config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  root to: 'home#index'
  resource :multiple_records, only: [:create, :destroy]

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title,
            length: { minimum: 8, maximum: 450 }

  validates :description,
            length: { maximum: 300 },
            allow_nil: true

  validates :accepted_terms, acceptance: true

  belongs_to :author, class_name: 'Writer', foreign_key: 'writer_id'
end

app/models/project.rb
class Project < ApplicationRecord
  validates_with ProjectValidator

  has_many :writers
  has_many :articles, through: :writers
end

app/models/writer.rb
class Writer < ApplicationRecord
  has_many :articles, foreign_key: 'writer_id'
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :index, locals: {
      projects: Project.all,
      writers: Writer.all,
      articles: Article.all
    }
  end
end

app/controllers/multiple_records_controller.rb
class MultipleRecordsController < ApplicationController
  def create
    AddNewRecordsWorker.perform_in(10.seconds)
    # CreateNewRecords.call
    redirect_to root_path
  end

  def destroy
    CleanUpRecordsWorker.perform_in(10.seconds)
    # CleanUpRecords.call
    redirect_to root_path
  end
end

# delayed job example
# def create
#   CreateNewRecords.delay.call
#   redirect_to root_path
# end

# sidekiq example
# def create
#   HardWorker.perform_in(4.seconds)
#   HardWorker.perform_async
#   redirect_to root_path
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<hr/>
<%= link_to 'add', multiple_records_path, method: :post %>
<%= link_to 'cleanup', multiple_records_path, method: :delete %>
<hr/>

<h3>Projects</h3>
<ul>
  <% projects.each do |project| %>
    <li>
      <pre><%= project.attributes %></pre>
    </li>
  <% end %>
</ul>

<h3>Writers</h3>
<ul>
  <% writers.each do |writer| %>
    <li>
      <pre><%= writer.attributes %></pre>
    </li>
  <% end %>
</ul>

<h3>Article</h3>
<ul>
  <% articles.each do |article| %>
    <li>
      <pre><%= article.attributes %></pre>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playground</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>